<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class RuleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
      
        $data = [
            ["Fase 1", "Kurang", "Pendek", "Kecil", "Gizi Baik"],
            ["Fase 1", "Kurang", "Pendek", "Sedang", "Gizi Baik"],
            ["Fase 1", "Kurang", "Pendek", "Besar", "Gizi Baik"],
            ["Fase 1", "Kurang", "Sedang", "Kecil", "Gizi Baik"],
            ["Fase 1", "Kurang", "Sedang", "Sedang", "Gizi Baik"],
            ["Fase 1", "Kurang", "Sedang", "Besar", "Gizi Baik"],
            ["Fase 1", "Kurang", "Tinggi", "Kecil", "Gizi Kurang"],
            ["Fase 1", "Kurang", "Tinggi", "Sedang", "Gizi Kurang"],
            ["Fase 1", "Kurang", "Tinggi", "Besar", "Gizi Kurang"],
            ["Fase 1", "Sedang", "Pendek", "Kecil", "Gizi Lebih"],
            ["Fase 1", "Sedang", "Pendek", "Sedang", "Gizi Lebih"],
            ["Fase 1", "Sedang", "Pendek", "Besar", "Gizi Lebih"],
            ["Fase 1", "Sedang", "Sedang", "Kecil", "Gizi Lebih"],
            ["Fase 1", "Sedang", "Sedang", "Sedang", "Gizi Lebih"],
            ["Fase 1", "Sedang", "Sedang", "Besar", "Gizi Lebih"],
            ["Fase 1", "Sedang", "Tinggi", "Kecil", "Gizi Lebih"],
            ["Fase 1", "Sedang", "Tinggi", "Sedang", "Gizi Lebih"],
            ["Fase 1", "Sedang", "Tinggi", "Besar", "Gizi Lebih"],
            ["Fase 1", "Lebih", "Pendek", "Kecil", "Gizi Lebih"],
            ["Fase 1", "Lebih", "Pendek", "Sedang", "Gizi Lebih"],
            ["Fase 1", "Lebih", "Pendek", "Besar", "Gizi Lebih"],
            ["Fase 1", "Lebih", "Sedang", "Kecil", "Gizi Lebih"],
            ["Fase 1", "Lebih", "Sedang", "Sedang", "Gizi Lebih"],
            ["Fase 1", "Lebih", "Sedang", "Besar", "Gizi Lebih"],
            ["Fase 1", "Lebih", "Tinggi", "Kecil", "Obesitas"],
            ["Fase 1", "Lebih", "Tinggi", "Sedang", "Obesitas"],
            ["Fase 1", "Lebih", "Tinggi", "Besar", "Obesitas"],
            ["Fase 2", "Kurang", "Pendek", "Kecil", "Gizi Kurang"],
            ["Fase 2", "Kurang", "Pendek", "Sedang", "Gizi Kurang"],
            ["Fase 2", "Kurang", "Pendek", "Besar", "Gizi Kurang"],
            ["Fase 2", "Kurang", "Sedang", "Kecil", "Gizi Kurang"],
            ["Fase 2", "Kurang", "Sedang", "Sedang", "Gizi Kurang"],
            ["Fase 2", "Kurang", "Sedang", "Besar", "Gizi Kurang"],
            ["Fase 2", "Kurang", "Tinggi", "Kecil", "Gizi Kurang"],
            ["Fase 2", "Kurang", "Tinggi", "Sedang", "Gizi Kurang"],
            ["Fase 2", "Kurang", "Tinggi", "Besar", "Gizi Kurang"],
            ["Fase 2", "Sedang", "Pendek", "Kecil", "Gizi Baik"],
            ["Fase 2", "Sedang", "Pendek", "Sedang", "Gizi Baik"],
            ["Fase 2", "Sedang", "Pendek", "Besar", "Gizi Baik"],
            ["Fase 2", "Sedang", "Sedang", "Kecil", "Gizi Baik"],
            ["Fase 2", "Sedang", "Sedang", "Sedang", "Gizi Baik"],
            ["Fase 2", "Sedang", "Sedang", "Besar", "Gizi Baik"],
            ["Fase 2", "Sedang", "Tinggi", "Kecil", "Gizi Baik"],
            ["Fase 2", "Sedang", "Tinggi", "Sedang", "Gizi Baik"],
            ["Fase 2", "Sedang", "Tinggi", "Besar", "Gizi Baik"],
            ["Fase 2", "Lebih", "Pendek", "Kecil", "Gizi Lebih"],
            ["Fase 2", "Lebih", "Pendek", "Sedang", "Gizi Lebih"],
            ["Fase 2", "Lebih", "Pendek", "Besar", "Gizi Lebih"],
            ["Fase 2", "Lebih", "Sedang", "Kecil", "Gizi Lebih"],
            ["Fase 2", "Lebih", "Sedang", "Sedang", "Gizi Lebih"],
            ["Fase 2", "Lebih", "Sedang", "Besar", "Gizi Lebih"],
            ["Fase 2", "Lebih", "Tinggi", "Kecil", "Obesitas"],
            ["Fase 2", "Lebih", "Tinggi", "Sedang", "Obesitas"],
            ["Fase 2", "Lebih", "Tinggi", "Besar", "Obesitas"],
            ["Fase 3", "Kurang", "Pendek", "Kecil", "Gizi Kurang"],
            ["Fase 3", "Kurang", "Pendek", "Sedang", "Gizi Kurang"],
            ["Fase 3", "Kurang", "Pendek", "Besar", "Gizi Kurang"],
            ["Fase 3", "Kurang", "Sedang", "Kecil", "Gizi Kurang"],
            ["Fase 3", "Kurang", "Sedang", "Sedang", "Gizi Kurang"],
            ["Fase 3", "Kurang", "Sedang", "Besar", "Gizi Kurang"],
            ["Fase 3", "Kurang", "Tinggi", "Kecil", "Gizi Kurang"],
            ["Fase 3", "Kurang", "Tinggi", "Sedang", "Gizi Kurang"],
            ["Fase 3", "Kurang", "Tinggi", "Besar", "Gizi Kurang"],
            ["Fase 3", "Sedang", "Pendek", "Kecil", "Gizi Baik"],
            ["Fase 3", "Sedang", "Pendek", "Sedang", "Gizi Baik"],
            ["Fase 3", "Sedang", "Pendek", "Besar", "Gizi Baik"],
            ["Fase 3", "Sedang", "Sedang", "Kecil", "Gizi Baik"],
            ["Fase 3", "Sedang", "Sedang", "Sedang", "Gizi Baik"],
            ["Fase 3", "Sedang", "Sedang", "Besar", "Gizi Baik"],
            ["Fase 3", "Sedang", "Tinggi", "Kecil", "Gizi Kurang"],
            ["Fase 3", "Sedang", "Tinggi", "Sedang", "Gizi Baik"],
            ["Fase 3", "Sedang", "Tinggi", "Besar", "Gizi Baik"],
            ["Fase 3", "Lebih", "Pendek", "Kecil", "Gizi Lebih"],
            ["Fase 3", "Lebih", "Pendek", "Sedang", "Gizi Lebih"],
            ["Fase 3", "Lebih", "Pendek", "Besar", "Gizi Lebih"],
            ["Fase 3", "Lebih", "Sedang", "Kecil", "Gizi Lebih"],
            ["Fase 3", "Lebih", "Sedang", "Sedang", "Gizi Lebih"],
            ["Fase 3", "Lebih", "Sedang", "Besar", "Gizi Lebih"],
            ["Fase 3", "Lebih", "Tinggi", "Kecil", "Obesitas"],
            ["Fase 3", "Lebih", "Tinggi", "Sedang", "Obesitas"],
            ["Fase 3", "Lebih", "Tinggi", "Besar", "Obesitas"],
            ["Fase 4", "Kurang", "Pendek", "Kecil", "Gizi Kurang"],
            ["Fase 4", "Kurang", "Pendek", "Sedang", "Gizi Kurang"],
            ["Fase 4", "Kurang", "Pendek", "Besar", "Gizi Kurang"],
            ["Fase 4", "Kurang", "Sedang", "Kecil", "Gizi Kurang"],
            ["Fase 4", "Kurang", "Sedang", "Sedang", "Gizi Kurang"],
            ["Fase 4", "Kurang", "Sedang", "Besar", "Gizi Kurang"],
            ["Fase 4", "Kurang", "Tinggi", "Kecil", "Gizi Kurang"],
            ["Fase 4", "Kurang", "Tinggi", "Sedang", "Gizi Kurang"],
            ["Fase 4", "Kurang", "Tinggi", "Besar", "Gizi kurang"],
            ["Fase 4", "Sedang", "Pendek", "Kecil", "Gizi kurang"],
            ["Fase 4", "Sedang", "Pendek", "Sedang", "Gizi Baik"],
            ["Fase 4", "Sedang", "Pendek", "Besar", "Gizi Baik"],
            ["Fase 4", "Sedang", "Sedang", "Kecil", "Gizi kurang"],
            ["Fase 4", "Sedang", "Sedang", "Sedang", "Gizi Baik"],
            ["Fase 4", "Sedang", "Sedang", "Besar", "Gizi Baik"],
            ["Fase 4", "Sedang", "Tinggi", "Kecil", "Gizi kurang"],
            ["Fase 4", "Sedang", "Tinggi", "Sedang", "Gizi Baik"],
            ["Fase 4", "Sedang", "Tinggi", "Besar", "Gizi Baik"],
            ["Fase 4", "Lebih", "Pendek", "Kecil", "Gizi Lebih"],
            ["Fase 4", "Lebih", "Pendek", "Sedang", "Gizi Lebih"],
            ["Fase 4", "Lebih", "Pendek", "Besar", "Gizi Lebih"],
            ["Fase 4", "Lebih", "Sedang", "Kecil", "Gizi Lebih"],
            ["Fase 4", "Lebih", "Sedang", "Sedang", "Gizi Lebih"],
            ["Fase 4", "Lebih", "Sedang", "Besar", "Gizi Lebih"],
            ["Fase 4", "Lebih", "Tinggi", "Kecil", "Gizi Baik"],
            ["Fase 4", "Lebih", "Tinggi", "Sedang", "Gizi Baik"],
            ["Fase 4", "Lebih", "Tinggi", "Besar", "Gizi Baik"],
            ["Fase 5", "Kurang", "Pendek", "Kecil", "Gizi Buruk"],
            ["Fase 5", "Kurang", "Pendek", "Sedang", "Gizi Buruk"],
            ["Fase 5", "Kurang", "Pendek", "Besar", "Gizi Buruk"],
            ["Fase 5", "Kurang", "Sedang", "Kecil", "Gizi Buruk"],
            ["Fase 5", "Kurang", "Sedang", "Sedang", "Gizi Buruk"],
            ["Fase 5", "Kurang", "Sedang", "Besar", "Gizi Buruk"],
            ["Fase 5", "Kurang", "Tinggi", "Kecil", "Gizi Buruk"],
            ["Fase 5", "Kurang", "Tinggi", "Sedang", "Gizi Buruk"],
            ["Fase 5", "Kurang", "Tinggi", "Besar", "Gizi Buruk"],
            ["Fase 5", "Sedang", "Pendek", "Kecil", "Gizi Kurang"],
            ["Fase 5", "Sedang", "Pendek", "Sedang", "Gizi Kurang"],
            ["Fase 5", "Sedang", "Pendek", "Besar", "Gizi Kurang"],
            ["Fase 5", "Sedang", "Sedang", "Kecil", "Gizi Kurang"],
            ["Fase 5", "Sedang", "Sedang", "Sedang", "Gizi Kurang"],
            ["Fase 5", "Sedang", "Sedang", "Besar", "Gizi Kurang"],
            ["Fase 5", "Sedang", "Tinggi", "Kecil", "Gizi Kurang"],
            ["Fase 5", "Sedang", "Tinggi", "Sedang", "Gizi Baik"],
            ["Fase 5", "Sedang", "Tinggi", "Besar", "Gizi Baik"],
            ["Fase 5", "Lebih", "Pendek", "Kecil", "Gizi Lebih"],
            ["Fase 5", "Lebih", "Pendek", "Sedang", "Gizi Lebih"],
            ["Fase 5", "Lebih", "Pendek", "Besar", "Gizi Lebih"],
            ["Fase 5", "Lebih", "Sedang", "Kecil", "Gizi Lebih"],
            ["Fase 5", "Lebih", "Sedang", "Sedang", "Gizi Lebih"],
            ["Fase 5", "Lebih", "Sedang", "Besar", "Gizi Lebih"],
            ["Fase 5", "Lebih", "Tinggi", "Kecil", "Gizi Baik"],
            ["Fase 5", "Lebih", "Tinggi", "Sedang", "Gizi Baik"],
            ["Fase 5", "Lebih", "Tinggi", "Besar", "Gizi Baik"]
        ];

        DB::table('rules')->insert([
            'name' => Str::random(10),
            'email' => Str::random(10) . '@gmail.com',
            'password' => Hash::make('password'),
        ]);
        Role::insert($data);
    }
}
